name: Snyk test of Docker image
on: push

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Snyk Auth
      run: |
        snyk auth $SNYK_TOKEN

    - name: Snyk scan
      run: |
        snyk container test debian --file=./Dockerfile

